import { createFooterFunction } from '../builders/pdf-footer.builder';
import { formatDate, formatNumberWithCommas, joinNonEmpty } from '../helpers/pdf-formatters';
import { ReceiptPdfData } from '../interfaces/pdf-document.interfaces';
import { PDF_DEFAULT_CONFIG, PDF_TABLE_LAYOUTS, getPdfStyles } from '../styles/pdf-styles';

const RECEIPT_LINE_WIDTH = 0.5;

function toNumber(value: any): number {
  const n = Number(value);
  return Number.isFinite(n) ? n : 0;
}

function normalizeCountry(value: any): string {
  return String(value || '').trim().toLowerCase();
}

function normalizeCurrencyCode(value: any): string {
  return String(value || '').trim().toUpperCase();
}

function getCurrencyConfig(data: ReceiptPdfData, currencyCode: any): any {
  const code = normalizeCurrencyCode(currencyCode);
  if (!code || !Array.isArray(data.currencyList)) return null;

  return data.currencyList.find((currency: any) => {
    const currencyMasterCode = normalizeCurrencyCode(
      currency?.currencyCode ||
      currency?.CurrencyCode ||
      currency?.code
    );
    const status = String(currency?.status || currency?.Status || 'A').trim().toUpperCase();
    return currencyMasterCode === code && status === 'A';
  }) || null;
}

function getCurrencyAmountDecimals(currency: any): number {
  const decimals = Number(currency?.amountDecimal ?? currency?.AmountDecimal);
  return Number.isFinite(decimals) ? decimals : 2;
}

function getCurrencyGroupingStyle(currency: any): 'Indian' | 'International' {
  return String(currency?.GroupingStyle || currency?.groupingStyle || '').trim() === 'Indian'
    ? 'Indian'
    : 'International';
}

function getCurrencyGroupSeparator(currency: any): string {
  return String(currency?.GroupSeparator || currency?.groupSeparator || '').trim() === 'Space'
    ? ' '
    : ',';
}

function groupIntegerPart(intDigits: string, style: 'Indian' | 'International', separator: string): string {
  if (style === 'Indian' && intDigits.length > 3) {
    const last3 = intDigits.slice(-3);
    const rest = intDigits.slice(0, -3);
    return rest.replace(/\B(?=(\d{2})+(?!\d))/g, separator) + separator + last3;
  }

  return intDigits.replace(/\B(?=(\d{3})+(?!\d))/g, separator);
}

function formatCurrencyAmount(data: ReceiptPdfData, value: any, currencyCode?: string): string {
  const currency = getCurrencyConfig(data, currencyCode || data.receipt?.currencyCode || '');
  const decimals = getCurrencyAmountDecimals(currency);
  const groupingStyle = getCurrencyGroupingStyle(currency);
  const groupSeparator = getCurrencyGroupSeparator(currency);
  const rounded = Number(toNumber(value).toFixed(decimals));
  const [intPart, decPart] = Math.abs(rounded).toFixed(decimals).split('.');
  const grouped = groupIntegerPart(intPart, groupingStyle, groupSeparator);
  const body = decPart ? `${grouped}.${decPart}` : grouped;

  return `${rounded < 0 ? '-' : ''}${body}`;
}

function formatReceiptCurrencyAmount(data: ReceiptPdfData, value: any): string {
  return formatCurrencyAmount(data, value, data.receipt?.currencyCode || '');
}

function resolveLedgerName(coaList: any[], coaMasterSid: any): string {
  if (!coaMasterSid || !Array.isArray(coaList)) return '';
  return coaList.find((v: any) => Number(v?.COAMasterSid) === Number(coaMasterSid))?.LedgerName || '';
}

function resolveSubledgerName(ledgerList: any[], ledgerMasterSid: any): string {
  if (!ledgerMasterSid || !Array.isArray(ledgerList)) return '';
  const flattenedLedgerList = ledgerList.flatMap((ledger: any) => Array.isArray(ledger) ? ledger : [ledger]);
  const subledger = flattenedLedgerList.find(
    (ledger: any) =>
      Number(ledger?.LedgerMasterSid) === Number(ledgerMasterSid) ||
      Number(ledger?.SubledgerMasterSid) === Number(ledgerMasterSid)
  );
  return subledger?.LedgerName || subledger?.SubledgerName || subledger?.CustomerName || '';
}

function getPrintLedgerDisplay(item: any, apiData: any, coaList: any[], ledgerList: any[]): string {
  if (!item) return '';

  const ledgerName = resolveLedgerName(coaList, item?.COAMasterSid);
  if (Number(item?.COAMasterSid) === Number(apiData?.BankCOA)) {
    return apiData?.BankPartyName || apiData?.PartyName || ledgerName;
  }

  if (item?.LedgerMasterSid) {
    return resolveSubledgerName(ledgerList, item.LedgerMasterSid) || ledgerName;
  }

  return ledgerName;
}

function getHeaderLedgerDisplay(apiData: any, receiptType: 'bank' | 'cash', coaList: any[], ledgerList: any[]): string {
  const voucherDetails = apiData?.VoucherDetail || [];
  const detailRow = voucherDetails.find(
    (item: any) =>
      item?.IsAutoGenerated !== 'Y' &&
      (receiptType === 'cash' || Number(item?.COAMasterSid) !== Number(apiData?.BankCOA))
  );

  if (receiptType === 'cash' && detailRow?.LedgerMasterSid) {
    const subledgerName = resolveSubledgerName(ledgerList, detailRow.LedgerMasterSid);
    if (subledgerName) {
      return subledgerName;
    }
  }

  if (detailRow?.COAMasterSid) {
    return resolveLedgerName(coaList, detailRow.COAMasterSid);
  }

  return resolveLedgerName(coaList, apiData?.COAMasterSid);
}

function buildCompanyHeader(data: ReceiptPdfData): any {
  const company = data.company;
  const branch = data.branch;
  const logo = data.logo;
  const printSettings = data.printSettings || {
    logoPosition: 'left' as const,
    companyPosition: 'center' as const,
    companyAlignment: 'center' as const
  };

  const city = branch?.cityMaster?.cityName || branch?.cityName || company?.city || '';
  const postalCode = branch?.postalCode || company?.postalCode || '';
  const phone = branch?.phoneNumber || company?.phoneNumber || '';

  const cityLine = buildHeaderDetailLine([
    { value: branch?.addressLine2 || company?.addressLine2 || '' },
    { value: city },
    { label: 'Postal Code : ', value: postalCode },
    { label: 'Ph.no : ', value: phone }
  ]);

  const companyInfoStack: any[] = [
    {
      text: (company?.companyName || '').toUpperCase(),
      fontSize: 14,
      bold: true,
      alignment: printSettings.companyAlignment
    },
    {
      text: branch?.branchName || '',
      fontSize: 11,
      bold: true,
      alignment: printSettings.companyAlignment,
      margin: [0, 1, 0, 0]
    },
    {
      text: branch?.addressLine1 || company?.addressLine1 || '',
      fontSize: 9,
      alignment: printSettings.companyAlignment,
      margin: [0, 1, 0, 0]
    },
    {
      text: cityLine,
      fontSize: 9,
      alignment: printSettings.companyAlignment,
      margin: [0, 1, 0, 6],
      noWrap: true
    }
  ];

  const slotAlign: Record<'left' | 'center' | 'right', 'left' | 'center' | 'right'> = {
    left: 'left',
    center: 'center',
    right: 'right'
  };

  const buildSlot = (slot: 'left' | 'center' | 'right') => {
    const stack: any[] = [];
    if (printSettings.logoPosition === slot && logo) {
      stack.push({ image: logo, fit: [60, 60], alignment: slotAlign[slot], margin: [8, 0, 15, 0] });
    }
    if (printSettings.companyPosition === slot) {
      const companyMargin = slot === 'right'
        ? (stack.length ? [0, 4, 18, 0] : [0, 0, 18, 0])
        : (stack.length ? [0, 4, 0, 0] : [0, 0, 0, 0]);
      stack.push({ stack: companyInfoStack, margin: companyMargin });
    }
    return { stack };
  };

  return {
    stack: [
      {
        table: {
          widths: getHeaderWidths(printSettings.logoPosition, printSettings.companyPosition),
          body: [[buildSlot('left'), buildSlot('center'), buildSlot('right')]]
        },
        layout: {
          hLineWidth: (i: number, node: any) => (i === node.table.body.length ? RECEIPT_LINE_WIDTH : 0),
          vLineWidth: () => 0,
          hLineColor: () => '#000000',
          paddingLeft: () => 0,
          paddingRight: () => 0,
          paddingTop: () => 0,
          paddingBottom: () => 6
        },
        margin: [0, 5, 0, 5]
      }
    ]
  };
}

function buildHeaderDetailLine(parts: Array<{ label?: string; value: string }>): any[] {
  return parts
    .filter(part => !!part.value)
    .flatMap((part, index) => [
      ...(index > 0 ? [{ text: ', ' }] : []),
      ...(part.label ? [{ text: part.label, bold: true }] : []),
      { text: part.value }
    ]);
}

function getHeaderWidths(
  logoPosition: 'left' | 'center' | 'right',
  companyPosition: 'left' | 'center' | 'right'
): any[] {
  if (companyPosition === 'center' && logoPosition !== 'center') {
    return [110, '*', 110];
  }

  if (companyPosition === 'right' && logoPosition === 'left') {
    return [110, '*', 300];
  }

  if (companyPosition === 'left' && logoPosition === 'right') {
    return [300, '*', 110];
  }

  return ['33%', '34%', '33%'];
}

function buildTitle(data: ReceiptPdfData): any {
  const baseTitle = data.receiptType === 'bank' ? 'Bank Receipt' : 'Cash Receipt';

  return {
    text: `${baseTitle}${data.receipt?.isDraft ? ' (DRAFT)' : ''}`,
    alignment: 'center',
    bold: true,
    fontSize: 12,
    margin: [0, 0, 0, 8]
  };
}

function infoRow(label: string, value: any): any {
  return {
    columns: [
      { text: label, width: 70, style: 'labelBold' },
      { text: ':', width: 8 },  
      { text: value ?? '', width: '*' }
    ],
    columnGap: 0,              
    margin: [0, 0, 0, 4]
  };
}

function valueOnlyRow(value: any): any {
  return {
    columns: [
      { text: '', width: 70 },
      { text: '', width: 8 },
      { text: value ?? '', width: '*' }
    ],
    columnGap: 0,
    margin: [0, 0, 0, 4]
  };
}

function buildInfoSection(data: ReceiptPdfData): any {
  const r: any = data.receipt || {};
  const leftStack: any[] = [];

  if (data.receiptType === 'bank') {
    leftStack.push(infoRow('Received From', r.partyName || ''));
    if (r.partyAddress) {
      leftStack.push(valueOnlyRow(r.partyAddress));
    }
    leftStack.push(infoRow('Receipt No.', r.voucherNumber || ''));
    leftStack.push(infoRow('Bank', r.bankName || ''));
  } else {
    leftStack.push(infoRow('Receipt No.', r.voucherNumber || ''));
    leftStack.push(infoRow('Received From', r.partyName || ''));
    if (r.partyAddress) {
      leftStack.push(valueOnlyRow(r.partyAddress));
    }
  }

  const rightStack: any[] = [
    infoRow('Receipt Date', r.voucherDate ? formatDate(r.voucherDate) : ''),
    infoRow('Currency', r.currencyCode || '')
  ];
  if (data.receiptType === 'bank') {
    rightStack.push(infoRow('Ex. Rate', formatNumberWithCommas(toNumber(r.exchangeRate), 3)));
    rightStack.push(infoRow('Payment Mode', joinNonEmpty([r.instrumentMode, r.instrumentNumber, r.instrumentDate ? formatDate(r.instrumentDate) : ''], ' / ')));
  }

 return {
  columns: [
    { width: 'auto', stack: leftStack },
    { width: 'auto', stack: rightStack }
  ],
  columnGap: 40,   
  margin: [55, 0, 0, 6]   
};
}

function buildDetailsTable(data: ReceiptPdfData): any {
  const header = [
    { text: 'Ledger', style: 'tableHeader', alignment: 'center', fontSize: 8 },
    { text: 'Description', style: 'tableHeader', alignment: 'center', fontSize: 8 },
    { text: 'Curr.', style: 'tableHeader', alignment: 'center', fontSize: 8 },
    { text: 'Ex.Rate', style: 'tableHeader', alignment: 'center', fontSize: 8 },
    { text: 'Amount', style: 'tableHeader', alignment: 'center', fontSize: 8 },
    { text: `${data.receipt.currencyCode || ''} Amount`, style: 'tableHeader', alignment: 'center', fontSize: 8 }
  ];

  const rows: any[] = (data.details || []).map((item) => ([
    { text: item.ledgerName || '', style: 'tableCellSmall',margin: [2, 0, 0, 0] },
    { text: item.narration || '', style: 'tableCellSmall', margin: [2, 0, 0, 0] },
    { text: item.currencyCode || '', style: 'tableCellSmall', alignment: 'center' },
    { text: formatNumberWithCommas(toNumber(item.exchangeRate), 3), style: 'tableCellSmall', alignment: 'right', noWrap: true, margin: [0, 0, 2, 0] },
    { text: formatCurrencyAmount(data, item.amount, item.currencyCode), style: 'tableCellSmall', alignment: 'right', noWrap: true, fontSize: 8, margin: [0, 0, 2, 0] },
    { text: formatReceiptCurrencyAmount(data, item.partyAmount), style: 'tableCellSmall', alignment: 'right', noWrap: true, fontSize: 8, margin: [0, 0, 2, 0] }
  ]));

  rows.push([
    { text: '', style: 'tableCellSmall',margin: [2, 0, 0, 0] },
    { text: '', style: 'tableCellSmall',margin: [2, 0, 0, 0] },
    { text: '', style: 'tableCellSmall' ,margin: [2, 0, 0, 0]},
    { text: '', style: 'tableCellSmall',margin: [2, 0, 0, 0] },
    { text: 'Total', style: 'tableCellBoldSmall', alignment: 'right',margin: [0, 0, 2, 0] },
    { text: formatReceiptCurrencyAmount(data, data.totals.totalAmount), style: 'tableCellBoldSmall', alignment: 'right', noWrap: true, fontSize: 8, margin: [0, 0, 2, 0] }
  ]);

return {
  table: {
    headerRows: 1,
    widths: ['20%', '*', '4%', '7%', '15%', '15%'],
    body: [header, ...rows]
  },
  layout: {
    ...PDF_TABLE_LAYOUTS.bordered,

    paddingLeft: () => 0,
    paddingRight: () => 0,
    paddingTop: () => 4,
    paddingBottom: () => 4,
    hLineWidth: () => RECEIPT_LINE_WIDTH,
    vLineWidth: (i: number, node: any) => {
      if (i === 0 || i === node.table.widths.length) {
        return 0; 
      }
      return RECEIPT_LINE_WIDTH; 
    }
  },
  margin: [-10, 0, -10, 8]
};
}

function buildAmountInWords(data: ReceiptPdfData): any {
  const labelWidth = 115;

  return {
    columns: [
      { text: 'Amount in Words', style: 'labelBold', width: labelWidth, noWrap: true },
      { text: ':', width: 10, alignment: 'center' },
      { text: data.amountInWords || '', width: '*', noWrap: false, margin: [1, 0, 0, 0] }
    ],
    columnGap: 0,
    margin: data.receiptType === 'bank' ? [10, 0, 20, 8] : [10, 2, 20, 8]
  };
}

function buildRemittanceSection(data: ReceiptPdfData): any[] {
  const isIndia = normalizeCountry(data.currentUserCountry) === 'india';
  const rows = data.voucherMatchings || [];
  if (!rows.length || String(data.receipt?.postStatus || '').toUpperCase() !== 'P') return [];

  const header = [
    { text: 'Voucher No.', style: 'tableHeader', alignment: 'center', fontSize: 8 },
    { text: 'Type', style: 'tableHeader', alignment: 'center', fontSize: 8 },
    { text: 'Voucher Date', style: 'tableHeader', alignment: 'center', fontSize: 8 },
    { text: 'Curr.', style: 'tableHeader', alignment: 'center', fontSize: 8 },
    { text: 'Curr. Amt', style: 'tableHeader', alignment: 'center', fontSize: 8 },
    { text: 'Local Amount', style: 'tableHeader', alignment: 'center', fontSize: 8 }
  ];
  const widths: any[] = data.receiptType === 'bank'
    ? (isIndia
        ? ['17%', '4%', '9%', '5%', '12%', '12%', '8%', '33%']
        : ['20%', '4%', '10%', '5%', '12%', '12%', '37%'])
    : (isIndia
        ? ['17%', '4%', '9%', '5%', '12%', '12%', '8%', '33%']
        : ['20%', '4%', '10%', '5%', '12%', '12%', '37%']);
  if (isIndia) {
    header.push({ text: 'TDS Amount', style: 'tableHeader', alignment: 'center', fontSize: 8 });
  }
  header.push({ text: 'Narration', style: 'tableHeader', alignment: 'center', fontSize: 8 });

  const bodyRows = rows.map((r) => {
    const row: any[] = [
      { text: r.voucherNumber || '', style: 'tableCellSmall', noWrap: true, margin: [2, 0, 0, 0]  },
      { text: r.voucherType || '', style: 'tableCellSmall', alignment: 'center' },
      { text: r.voucherDate ? formatDate(r.voucherDate) : '', style: 'tableCellSmall', alignment: 'center' },
      { text: r.currencyCode || '', style: 'tableCellSmall', alignment: 'center' },
      { text: formatCurrencyAmount(data, r.matchingAmount, r.currencyCode), style: 'tableCellSmall', alignment: 'right', noWrap: true, margin: [0, 0, 2, 0]},
      { text: formatReceiptCurrencyAmount(data, r.matchingLocalAmount), style: 'tableCellSmall', alignment: 'right', noWrap: true, margin: [0, 0, 2, 0] }
    ];
    if (isIndia) row.push({ text: '', style: 'tableCellSmall', alignment: 'right' });
    row.push({
      text: r.narration || '',
      style: 'tableCellSmall',
      alignment: 'left',
      noWrap: false,
      margin: [4, 0, 4, 0]
    });
    return row;
  });

  const totalRow: any[] = [
    { text: 'Total', style: 'tableCellBoldSmall', alignment: 'right', colSpan: 4, margin: [0, 0, 2, 0] },
    {},
    {},
    {},
    { text: formatReceiptCurrencyAmount(data, data.totals.totalMatchingAmount), style: 'tableCellBoldSmall', alignment: 'right', noWrap: true, margin: [0, 0, 2, 0] },
    { text: formatReceiptCurrencyAmount(data, data.totals.totalMatchingLocalAmount), style: 'tableCellBoldSmall', alignment: 'right', noWrap: true, margin: [0, 0, 2, 0] }
  ];
  if (isIndia) totalRow.push({ text: '', style: 'tableCellBoldSmall', alignment: 'right', margin: [0, 0, 2, 0] });
  totalRow.push({ text: '', style: 'tableCellSmall', margin: [4, 0, 4, 0] });

  return [
    { text: 'Remittance Details', fontSize: 10, bold: false, margin: [-3, 7, 0, 2] },
    {
      table: {
        headerRows: 1,
        widths,
        body: [header, ...bodyRows, totalRow]
      },
       layout: {
    ...PDF_TABLE_LAYOUTS.bordered,

    paddingLeft: () => 2,
    paddingRight: () => 2,
    paddingTop: () => 3,
    paddingBottom: () => 3,
    hLineWidth: () => RECEIPT_LINE_WIDTH,
    vLineWidth: (i: number, node: any) => {
      if (i === 0 || i === node.table.widths.length) {
        return 0; 
      }
      return RECEIPT_LINE_WIDTH; 
    }
  },
      margin: [-10, 0, -10, 8]
    }
  ];
}

function buildSignatureSection(_data: ReceiptPdfData): any {
  return {
    columns: [
      { text: '', width: '*' },
      { text: 'Received By', bold: true, alignment: 'right', width: '*' }
    ],
    margin: [20, 24, 20, 0],
    absolutePosition: { x: 0, y: 770 }
  };
}

export function generateReceiptDocument(data: ReceiptPdfData): any {
  const configuredMargins = data.config?.pageMargins as number[] | undefined;
  const resolvedPageMargins = configuredMargins
    ? [
        configuredMargins[0] ?? 20,
        Math.max(configuredMargins[1] ?? 82, 82),
        configuredMargins[2] ?? 20,
        configuredMargins[3] ?? 28
      ]
    : [20, 82, 20, 28];

  return {
    pageSize: data.config?.pageSize || PDF_DEFAULT_CONFIG.pageSize,
    pageOrientation: data.config?.pageOrientation || PDF_DEFAULT_CONFIG.pageOrientation,
    pageMargins: resolvedPageMargins,
    header: () => ({
      stack: [buildCompanyHeader(data)],
      margin: [10, 10, 10, 0]
    }),
    background: (_currentPage: number, pageSize: any) => ({
      canvas: [
        { type: 'line', x1: 10, y1: 10, x2: pageSize.width - 10, y2: 10, lineWidth: RECEIPT_LINE_WIDTH },
        { type: 'line', x1: 10, y1: pageSize.height - 10, x2: pageSize.width - 10, y2: pageSize.height - 10, lineWidth: RECEIPT_LINE_WIDTH },
        { type: 'line', x1: 10, y1: 10, x2: 10, y2: pageSize.height - 10, lineWidth: RECEIPT_LINE_WIDTH },
        { type: 'line', x1: pageSize.width - 10, y1: 10, x2: pageSize.width - 10, y2: pageSize.height - 10, lineWidth: RECEIPT_LINE_WIDTH }
      ]
    }),
    content: [
      buildTitle(data),
      buildInfoSection(data),
      buildDetailsTable(data),
      buildAmountInWords(data),
      ...buildRemittanceSection(data),
      buildSignatureSection(data)
    ],
    footer: createFooterFunction(data.userData, {
      showPageNumbers: true,
      pageMargins: [20, 0, 20, 0]
    }),
    styles: getPdfStyles(),
    defaultStyle: PDF_DEFAULT_CONFIG.defaultStyle
  };
}

export function transformReceiptApiData(
  apiData: any,
  company: any,
  branch: any,
  userData: any,
  logo?: string,
  options?: {
    receiptType?: 'bank' | 'cash';
    coaList?: any[];
    bankTypedLedgers?: any[];
    ledgerList?: any[];
    amountInWords?: string;
    currentUserCountry?: string;
    currencyList?: any[];
    allowPrintBeforePosting?: boolean;
    printSettings?: {
      logoPosition: 'left' | 'center' | 'right';
      companyPosition: 'left' | 'center' | 'right';
      companyAlignment: 'left' | 'center' | 'right';
    };
  }
): ReceiptPdfData {
  const receiptType = options?.receiptType || 'cash';
  const coaList = options?.coaList || [];
  const bankTypedLedgers = options?.bankTypedLedgers || [];
  const ledgerList = options?.ledgerList || [];
  const statusValues = [
    apiData?.PostStatus,
    apiData?.postStatus,
    apiData?.Status,
    apiData?.status
  ].map((value) => String(value || '').trim().toUpperCase());
  const isDraft = statusValues.some((value) =>
    value === 'U' ||
    value === 'UNPOSTED' ||
    value === 'UNPOST'
  ) && !options?.allowPrintBeforePosting;

  const detailRows = (apiData?.VoucherDetail || [])
    .filter(
      (item: any) =>
        item?.DrCr === 'D' &&
        item?.IsAutoGenerated !== 'Y' &&
        toNumber(item?.LocalAmount) !== 0
    )
    .map((item: any) => {
      return {
        ledgerName: getPrintLedgerDisplay(item, apiData, coaList, ledgerList),
        narration: item?.Narration || '',
        currencyCode: item?.CurrencyCode || '',
        exchangeRate: toNumber(item?.ExchangeRate),
        amount: toNumber(item?.Amount),
        partyAmount: toNumber(item?.PartyAmount)
      };
    });

  const totalAmount = detailRows.reduce((sum: number, item: any) => sum + toNumber(item.partyAmount), 0);
  const voucherMatchings = (apiData?.voucherMatchings || []).map((m: any) => ({
    voucherNumber: m?.VoucherNumber || '',
    voucherType: m?.VoucherType || '',
    voucherDate: m?.VoucherDate || '',
    currencyCode: m?.CurrencyCode || '',
    matchingAmount: toNumber(m?.MatchingAmount),
    matchingLocalAmount: toNumber(m?.MatchingLocalAmount),
    tdsAmount: toNumber(m?.TDSAmount),
    narration: m?.Narration || apiData?.VoucherDetail?.[0]?.Narration || apiData?.Narration || ''
  }));

  const totalMatchingAmount = voucherMatchings.reduce((sum: number, item: any) => sum + toNumber(item.matchingAmount), 0);
  const totalMatchingLocalAmount = voucherMatchings.reduce((sum: number, item: any) => sum + toNumber(item.matchingLocalAmount), 0);

  const bank = bankTypedLedgers.find((b: any) => b?.COAMasterSid == apiData?.BankCOA);
  const headerLedgerDisplay = getHeaderLedgerDisplay(apiData, receiptType, coaList, ledgerList);

  return {
    company: {
      companyName: company?.companyName || company?.CompanyName || '',
      addressLine1: company?.addressLine1 || company?.Address || '',
      addressLine2: company?.addressLine2 || '',
      city: company?.city || '',
      postalCode: company?.postalCode || '',
      phoneNumber: company?.phoneNumber || company?.Phone || ''
    },
    branch: {
      branchName: branch?.branchName || branch?.BranchName || '',
      addressLine1: branch?.addressLine1 || branch?.Address || '',
      addressLine2: branch?.addressLine2 || '',
      cityName: branch?.cityMaster?.cityName || branch?.cityName || '',
      postalCode: branch?.postalCode || '',
      phoneNumber: branch?.phoneNumber || '',
      cityMaster: branch?.cityMaster
    },
    userData: {
      userName: userData?.userName || userData?.UserName || '',
      email: userData?.email || userData?.Email || ''
    },
    logo,
    printSettings: options?.printSettings || {
      logoPosition: 'left',
      companyPosition: 'center',
      companyAlignment: 'center'
    },
    receiptType,
    receipt: {
      voucherNumber: apiData?.VoucherNumber || '',
      voucherDate: apiData?.VoucherDate || '',
      partyName: apiData?.PartyName || '',
      partyAddress: apiData?.PartyAddress || '',
      currencyCode: apiData?.CurrencyCode || '',
      exchangeRate: toNumber(apiData?.ExchangeRate),
      bankName: bank?.LedgerName || '',
      headerLedgerDisplay,
      instrumentMode: apiData?.InstrumentMode || '',
      instrumentNumber: apiData?.InstrumentNumber || '',
      instrumentDate: apiData?.InstrumentDate || '',
      postStatus: String(apiData?.PostStatus || ''),
      isDraft
    },
    details: detailRows,
    voucherMatchings,
    totals: {
      totalAmount,
      totalMatchingAmount,
      totalMatchingLocalAmount
    },
    amountInWords:
      options?.amountInWords ||
      apiData?.AmountInWords ||
      apiData?.amountInWords ||
      '',
    currentUserCountry: options?.currentUserCountry || '',
    currencyList: options?.currencyList || []
  };
}
