export interface Branch {
    branchName: string,
    branchCode: string,
    createdOn?: Date,
    updatedOn?: Date,
    // deletedAt?: Date,
    createdBy: string,
    updatedBy?: string,
    taxRegistrationNo?: string,
    CISN?: string,
    addressLine1: string,
    addressLine2?: string,
    postalCode: string,
    webSite?: string,
    phoneNumber?: string,
    email?: string,
    timeZone?: string,
    remarks?: string,
    companyLogo?: number,
    reportLogo?: number,
    status: string,
    BranchMasterSid?: number,
    CityMasterSid: number,
    CompanyMasterSid: number,
    CountryMasterSid: number,
    CurrencyMasterSid: number,
    LoginSid?: number,
    StateMasterSid: number,

    company?: any,
    cityMaster?: any,
    stateMaster?: any
}
