export interface Lead {
    PreCustomerMasterSid: number,
    CompanyMasterSid: number,
    CityMasterSid: number,
    CountryMasterSid: number,
    StateMasterSid: number,
    BranchMasterSid: number,
    preCustomerName: String,
    preCustomerAddress1: string,
    preCustomerAddress2: string,
    leadAssignTo: number,
    customerType: string,
    contactPerson: string,
    email: string,
    phone: string,
    preCustomerType: string,
    leadReferredOn: string,
    leadReferredBy: string,
    panVat: string,
    remarks: string,
    createdOn: string,
    createdBy: string,
    updatedOn: string,
    updatedBy: string,
    status: string
}