export interface PreCustomer {
    PreCustomerMasterSid?: number,
    CompanyMasterSid: number,
    CityMasterSid: number,
    CountryMasterSid: number,
    StateMasterSid: number,
    BranchMasterSid: string,
    preCustomerName: string,
    preCustomerAddress1: string,
    preCustomerAddress2: string,
    leadAssignTo?: string,
    customerType?: string,
    contactPerson: string,
    email: string,
    phone: string,
    preCustomerType?: string,
    leadFrom: string,
    leadReferredBy: string,
    panVat?: string,
    remarks?: string,
    status: string,
    createdOn: string,
    createdBy: string,
    updatedOn: string,
    updatedBy: string
}