export interface Product {
    ProductMasterSId ?: number,
    CategoryMasterSId ?: number,
    CustomerMasterSid ?: number,
    CompanyMasterSid ?: number,
    ProductCode : string,
    ProductName : string,
    Product_LL ?: string,
    HSNCode ?: string,
    Description ?: string,
    UOMCode ?: string,
    ProductId ?: string,
    ImcoName ?: string,
    UNo ?: string,
    PackingGroup ?: string,
    ProductType ?: string,
    UNNo ?: number,
    IMOClass ?: string,
    IMOSubClass ?: string,
    UNPackingCode ?: string,
    FlashPoint ?: string,
    createdOn ?: Date,
    updatedOn ?: Date,
    // deletedAt ?: Date,
    createdBy : string,
    updatedBy ?: string,
    status ?: string,
    category ?: any[],
    customer ?:any[],
    company ?:any[] 
}