export interface Tariff {
    TariffHeaderSid?: string,
    SegmentMasterSid?: number,
    DepartmentName: string,
    POOSid: number,
    POLSid: number,
    PODSid: number,
    FDCSid: number,
    ViaPortSid: number,
    POLTerminal: string,
    PODTerminal: string,
    Carrier: number | string,
    CargoType: string,
    ServiceLevel: string,
    AgentSid: number,
    StuffingAt: string,
    IncoTerms: string,
    Remarks: string,
    status: string,
    EffectiveDate: Date,
    createdOn?: Date,
    updatedOn?: Date,
    // deletedAt?: Date,
    createdBy?: string,
    updatedBy?: string,
    IsSlabApplicable?: string
    customerCarrier ?:object,
    customerAgent ?:object,
    departmentMaster ?:object

}