export const iconsData: Record<string, { name: string; icon: string;size?: string  }[]> = {
  Setting: [
    { name: "Menu", icon: "fas fa-bars",size: "10px" },
    { name: "Module", icon: "fas fa-th-large" },
    { name: "Role", icon: "fas fa-user-shield" },
    { name: "Role Menu", icon: "fas fa-users-cog" }
  ],
  CRM: [
    { name: "Calendar", icon: "fas fa-calendar-alt" },
    { name: "Meeting Update", icon: "fas fa-handshake" },
    { name: "Quotation", icon: "fas fa-file-invoice-dollar" },
    { name: "Lead", icon: "fas fa-bullseye" },
    { name: "Opportunity", icon: "fas fa-calendar-check" },
    { name: "To Do", icon: "fas fa-tasks" },
    { name: "Enquiry", icon: "fas fa-question-circle" }
  ],
  Master: [
  { name: "Company", icon: "fas fa-building" },
  { name: "Cost Center", icon: "fas fa-wallet" },
  { name: "Document Type", icon: "fas fa-file-alt" },
  { name: "Profit Center", icon: "fas fa-coins" },
  { name: "Report", icon: "fas fa-chart-line" },
  { name: "TDS Set", icon: "fas fa-percent" },
  { name: "Year", icon: "fas fa-calendar-alt" },
  { name: "Airline", icon: "fas fa-plane" },
  { name: "BL Clause", icon: "fas fa-file-contract" },
  { name: "Charge", icon: "fas fa-money-bill-wave" },
  { name: "Charge Group", icon: "fas fa-layer-group" },
  { name: "Charge Tax", icon: "fas fa-receipt" },
  { name: "Container Activity Master", icon: "fas fa-boxes" },
  { name: "Container Type", icon: "fas fa-box" },
  { name: "Currency", icon: "fas fa-dollar-sign" },
 { name: "Department", icon: "fas fa-network-wired" },
  { name: "Division", icon: "fas fa-sitemap" },
  { name: "HAWB Stock", icon: "fas fa-box-open" },
  { name: "MAWB Stock", icon: "fas fa-chart-line" },
  { name: "HS SAC", icon: "fas fa-barcode" },
  { name: "Milestone", icon: "fas fa-flag-checkered" },
  { name: "Organization", icon: "fas fa-users" },
  { name: "Package Type", icon: "fas fa-boxes" },
  { name: "Port Master", icon: "fas fa-anchor" },
  { name: "Product", icon: "fas fa-gift" },
  { name: "Sailing Schedule", icon: "fas fa-ship" },
  { name: "Sector", icon: "fas fa-map-marked-alt" },
  { name: "Service Level", icon: "fas fa-headset" },
  { name: "Tariff", icon: "fas fa-file-invoice" },
  { name: "Unit", icon: "fas fa-cube" },
  { name: "UOM", icon: "fas fa-ruler-combined" },
{ name: "Vessel", icon: "fas fa-route" },
  { name: "Zone", icon: "fas fa-map" },
   { name: "Authorization", icon: "fas fa-user-shield" },
  { name: "City", icon: "fas fa-city" },
  { name: "Country", icon: "fas fa-globe" },
  { name: "Document Authorization", icon: "fas fa-file-signature" },
  { name: "Document Number Generation", icon: "fas fa-hashtag" },
  { name: "IMCO", icon: "fas fa-exclamation-triangle" },
  { name: "INCO", icon: "fas fa-file-contract" },
 { name: "State", icon: "fas fa-map-marked-alt" },
  { name: "Time Zone", icon: "fas fa-clock" },
  { name: "User", icon: "fas fa-user" }
  ],
  Operation: [
    { name: "Booking", icon: "fas fa-anchor" },
    { name: "Cargo Receipt", icon: "fas fa-receipt" },
    { name: "Invoice", icon: "fas fa-file-invoice" },
    { name: "Loading Plan", icon: "fas fa-truck-loading" },
    { name: "Master Job", icon: "fas fa-shipping-fast" },
    { name: "Merge Booking", icon: "fas fa-object-group" },
    { name: "Operation Reports", icon: "fas fa-chart-line" },
    { name: "Shipment Instruction", icon: "fas fa-clipboard-list" },
    { name: "Split Booking", icon: "fas fa-object-ungroup" },
    {name:"Master Air Waybill",icon:"fas fa-plane"},
    {name:"Service Job",icon:"fas fa-tools"}
  ],
  Account: [
    { name: "Chart of Accounts", icon: "fas fa-project-diagram" },
    { name: "Currency Exchange", icon: "fas fa-rupee-sign" },
    { name: "Subledger Mapping", icon: "fas fa-sitemap" },
    { name: "Supplier TDS Mapping", icon: "fas fa-user-tag" },
    { name: "Tax Group", icon: "fas fa-percent" }
  ]
};
